# Fix màu sắc cho Alacritty
set -g default-terminal "alacritty"
set -as terminal-overrides ",alacritty:Tc"
# status bar
set -g status-style bg=default

# Giảm delay phím Esc cho Neovim
set -s escape-time 0
set -g mouse on
set -g base-index 1

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind -n | split-window -h -c "#{pane_current_path}"

bind -n _ split-window -v -c "#{pane_current_path}"
