import json
import os
from pathlib import Path

# Setup paths
script_dir = Path(__file__).parent
dotfiles_dir = script_dir.parent
theme_json_path = dotfiles_dir / "themes" / "theme.json"
out_dir = dotfiles_dir / "themes" / "generated"

out_dir.mkdir(parents=True, exist_ok=True)

# Read theme JSON
with open(theme_json_path, "r", encoding="utf-8") as f:
    theme_data = json.load(f)

# Generate Lua
lua_content = "-- Auto-generated by generate_theme.py\nreturn {\n"
for key, value in theme_data.items():
    if key != "name":
        lua_content += f'  {key} = "{value}",\n'
lua_content += "}\n"

with open(out_dir / "theme.lua", "w", encoding="utf-8") as f:
    f.write(lua_content)

# Generate Shell (Bash)
sh_content = "# Auto-generated by generate_theme.py\n"
for key, value in theme_data.items():
    if key != "name":
        sh_content += f'export THEME_{key.upper()}="{value}"\n'

with open(out_dir / "theme.sh", "w", encoding="utf-8") as f:
    f.write(sh_content)

# Generate PowerShell
ps1_content = "# Auto-generated by generate_theme.py\n"
for key, value in theme_data.items():
    if key != "name":
        ps1_content += f'$env:THEME_{key.upper()}="{value}"\n'

with open(out_dir / "theme.ps1", "w", encoding="utf-8") as f:
    f.write(ps1_content)

print(f"Theme '{theme_data.get('name', 'Custom')}' compiled successfully to {out_dir}")
