import json
import os
from pathlib import Path

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore



def generate_lua(theme_data: dict, out_path: Path):
    lua_content = "-- Auto-generated by generate_theme.py\nreturn {\n"
    for key, value in theme_data.items():
        if key != "name":
            lua_content += f'  {key} = "{value}",\n'
    lua_content += "}\n"

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(lua_content)


def generate_sh(theme_data: dict, out_path: Path):
    sh_content = "# Auto-generated by generate_theme.py\n"
    for key, value in theme_data.items():
        if key != "name":
            sh_content += f'export THEME_{key.upper()}="{value}"\n'

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(sh_content)


def generate_ps1(theme_data: dict, out_path: Path):
    ps1_content = "# Auto-generated by generate_theme.py\n"
    for key, value in theme_data.items():
        if key != "name":
            ps1_content += f'$env:THEME_{key.upper()}="{value}"\n'

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(ps1_content)


def generate_toml(theme_data: dict, out_path: Path):
    toml_content = "# Auto-generated by generate_theme.py\n"
    for key, value in theme_data.items():
        if key != "name":
            toml_content += f'{key} = "{value}"\n'

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(toml_content)


def generate_atuin_theme(theme_toml_path: Path, out_path: Path):
    with open(theme_toml_path, "rb") as f:
        colors = tomllib.load(f)

    atuin_content = f"""# Auto-generated by generate_theme.py from {theme_toml_path.name}
[theme]
name = "theme"
parent = "default"

[colors]
AlertInfo = "{colors.get('blue', '#89b4fa')}"
AlertWarn = "{colors.get('yellow', '#f9e2af')}"
AlertError = "{colors.get('red', '#f38ba8')}"
Annotation = "{colors.get('cyan', '#94e2d5')}"
Base = "{colors.get('fg', '#cdd6f4')}"
Guidance = "{colors.get('green', '#a6e3a1')}"
Important = "{colors.get('magenta', '#f5c2e7')}"
Title = "{colors.get('blue', '#89b4fa')}"
Muted = "{colors.get('black', '#45475a')}"
SyntaxCommand = "{colors.get('blue', '#89b4fa')}"
SyntaxFlag = "{colors.get('cyan', '#94e2d5')}"
SyntaxString = "{colors.get('green', '#a6e3a1')}"
SyntaxVariable = "{colors.get('magenta', '#f5c2e7')}"
SyntaxOperator = "{colors.get('cyan', '#94e2d5')}"
SyntaxComment = "{colors.get('black', '#45475a')}"
"""

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(atuin_content)


def main():
    script_dir = Path(__file__).parent
    dotfiles_dir = script_dir.parent
    theme_json_path = dotfiles_dir / "themes" / "theme.json"
    out_dir = dotfiles_dir / "themes" / "generated"
    atuin_themes_dir = dotfiles_dir / "atuin" / "themes"

    out_dir.mkdir(parents=True, exist_ok=True)
    atuin_themes_dir.mkdir(parents=True, exist_ok=True)

    with open(theme_json_path, "r", encoding="utf-8") as f:
        theme_data = json.load(f)

    # 1. Sinh các tệp theme gốc (raw colors)
    generate_lua(theme_data, out_dir / "theme.lua")
    generate_sh(theme_data, out_dir / "theme.sh")
    generate_ps1(theme_data, out_dir / "theme.ps1")
    generate_toml(theme_data, out_dir / "theme.toml")

    # 2. Sinh theme cho Atuin bằng cách đọc từ themes/generated/theme.toml
    generate_atuin_theme(out_dir / "theme.toml", atuin_themes_dir / "theme.toml")

    print(f"Theme '{theme_data.get('name', 'Custom')}' compiled successfully to {out_dir} & {atuin_themes_dir}")


if __name__ == "__main__":
    main()
