use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ThemeData {
    #[serde(default = "default_theme_name")]
    pub name: String,
    pub bg: String,
    pub fg: String,
    pub black: String,
    pub red: String,
    pub green: String,
    pub yellow: String,
    pub blue: String,
    pub magenta: String,
    pub cyan: String,
    pub white: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

fn default_theme_name() -> String {
    "Custom".to_string()
}

impl ThemeData {
    /// Return the list of color key-value pairs in standard order.
    pub fn colors(&self) -> Vec<(&str, &str)> {
        let mut list = vec![
            ("bg", self.bg.as_str()),
            ("fg", self.fg.as_str()),
            ("black", self.black.as_str()),
            ("red", self.red.as_str()),
            ("green", self.green.as_str()),
            ("yellow", self.yellow.as_str()),
            ("blue", self.blue.as_str()),
            ("magenta", self.magenta.as_str()),
            ("cyan", self.cyan.as_str()),
            ("white", self.white.as_str()),
        ];
        for (k, v) in &self.extra {
            if let Some(s) = v.as_str() {
                list.push((k.as_str(), s));
            }
        }
        list
    }
}

pub fn generate_lua(theme: &ThemeData) -> String {
    let mut out = String::from("-- Auto-generated by generate_theme.py\nreturn {\n");
    for (key, value) in theme.colors() {
        out.push_str(&format!("  {} = \"{}\",\n", key, value));
    }
    out.push_str("}\n");
    out
}

pub fn generate_sh(theme: &ThemeData) -> String {
    let mut out = String::from("# Auto-generated by generate_theme.py\n");
    for (key, value) in theme.colors() {
        out.push_str(&format!("export THEME_{}=\"{}\"\n", key.to_uppercase(), value));
    }
    out
}

pub fn generate_ps1(theme: &ThemeData) -> String {
    let mut out = String::from("# Auto-generated by generate_theme.py\n");
    for (key, value) in theme.colors() {
        out.push_str(&format!("$env:THEME_{}=\"{}\"\n", key.to_uppercase(), value));
    }
    out
}

pub fn generate_toml(theme: &ThemeData) -> String {
    let mut out = String::from("# Auto-generated by generate_theme.py\n");
    for (key, value) in theme.colors() {
        out.push_str(&format!("{} = \"{}\"\n", key, value));
    }
    out
}

pub fn generate_atuin_theme(theme: &ThemeData) -> String {
    format!(
r#"# Auto-generated by generate_theme.py from theme.toml
[theme]
name = "theme"
parent = "default"

[colors]
AlertInfo = "{blue}"
AlertWarn = "{yellow}"
AlertError = "{red}"
Annotation = "{cyan}"
Base = "{fg}"
Guidance = "{green}"
Important = "{magenta}"
Title = "{blue}"
Muted = "{black}"
SyntaxCommand = "{blue}"
SyntaxFlag = "{cyan}"
SyntaxString = "{green}"
SyntaxVariable = "{magenta}"
SyntaxOperator = "{cyan}"
SyntaxComment = "{black}"
"#,
        blue = theme.blue,
        yellow = theme.yellow,
        red = theme.red,
        cyan = theme.cyan,
        fg = theme.fg,
        green = theme.green,
        magenta = theme.magenta,
        black = theme.black
    )
}

/// Parses theme.json and generates theme.lua, theme.sh, theme.ps1, theme.toml, and atuin theme.toml.
pub fn generate_themes(dotfiles_dir: &Path) -> Result<ThemeData> {
    let theme_json_path = dotfiles_dir.join("themes").join("theme.json");
    let content = fs::read_to_string(&theme_json_path)
        .with_context(|| format!("Không thể đọc tệp theme: {}", theme_json_path.display()))?;

    let theme_data: ThemeData = serde_json::from_str(&content)
        .with_context(|| format!("Lỗi phân tích JSON từ: {}", theme_json_path.display()))?;

    let out_dir = dotfiles_dir.join("themes").join("generated");
    let atuin_themes_dir = dotfiles_dir.join("atuin").join("themes");

    fs::create_dir_all(&out_dir)
        .with_context(|| format!("Không thể tạo thư mục: {}", out_dir.display()))?;
    fs::create_dir_all(&atuin_themes_dir)
        .with_context(|| format!("Không thể tạo thư mục: {}", atuin_themes_dir.display()))?;

    fs::write(out_dir.join("theme.lua"), generate_lua(&theme_data))
        .with_context(|| "Không thể ghi tệp theme.lua")?;
    fs::write(out_dir.join("theme.sh"), generate_sh(&theme_data))
        .with_context(|| "Không thể ghi tệp theme.sh")?;
    fs::write(out_dir.join("theme.ps1"), generate_ps1(&theme_data))
        .with_context(|| "Không thể ghi tệp theme.ps1")?;
    fs::write(out_dir.join("theme.toml"), generate_toml(&theme_data))
        .with_context(|| "Không thể ghi tệp theme.toml")?;

    fs::write(
        atuin_themes_dir.join("theme.toml"),
        generate_atuin_theme(&theme_data),
    )
    .with_context(|| "Không thể ghi tệp atuin theme.toml")?;

    Ok(theme_data)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_theme() -> ThemeData {
        serde_json::from_str(r##"{
            "name": "Catppuccin Mocha",
            "bg": "#1e1e2e",
            "fg": "#cdd6f4",
            "black": "#45475a",
            "red": "#f38ba8",
            "green": "#a6e3a1",
            "yellow": "#f9e2af",
            "blue": "#89b4fa",
            "magenta": "#f5c2e7",
            "cyan": "#94e2d5",
            "white": "#bac2de"
        }"##).unwrap()
    }


    #[test]
    fn test_theme_generation_output() {
        let theme = sample_theme();

        let lua = generate_lua(&theme);
        assert!(lua.contains("bg = \"#1e1e2e\","));
        assert!(lua.contains("fg = \"#cdd6f4\","));

        let sh = generate_sh(&theme);
        assert!(sh.contains("export THEME_BG=\"#1e1e2e\""));

        let ps1 = generate_ps1(&theme);
        assert!(ps1.contains("$env:THEME_BG=\"#1e1e2e\""));

        let toml = generate_toml(&theme);
        assert!(toml.contains("bg = \"#1e1e2e\""));

        let atuin = generate_atuin_theme(&theme);
        assert!(atuin.contains("AlertInfo = \"#89b4fa\""));
    }
}
